hl.on("hyprland.start", function()
  hl.exec_cmd("uwsm-app -- hypridle")
  hl.exec_cmd("uwsm-app -- mako")
  -- hl.exec_cmd("uwsm-app -- waybar")
  hl.exec_cmd("uwsm-app -t service -p Restart=on-failure -p RestartSec=2 -- ags run -d ~/.local/share/omarchy/config/ags --gtk 4")
  hl.exec_cmd("uwsm-app -- sunsetr --background")
  -- hl.exec_cmd("uwsm-app -- fcitx5")
  hl.exec_cmd("uwsm-app -- swaybg -i ~/.config/omarchy/current/background -m fill")
  hl.exec_cmd("uwsm-app -- swayosd-server")
  hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
  hl.exec_cmd("omarchy-cmd-first-run")
  hl.exec_cmd("uwsm-app -- elephant")
  hl.exec_cmd("uwsm-app -- walker --gapplication-service")

  -- Slow app launch fix -- set systemd vars
  hl.exec_cmd("systemctl --user import-environment $(env | cut -d'=' -f 1)")
  hl.exec_cmd("dbus-update-activation-environment --systemd --all")
end)
