windowrule = match:class Plex, opacity 1.0 1.0
windowrule = match:class Plex, no_anim true
windowrule = match:class Plex, no_blur true
windowrule = match:class Plex, opaque true
windowrule = match:class Plex, no_dim true

windowrule = match:float true, match:class ^(Plex)$, size 960 540
